platform :ios, '13.0'

target 'Flash Chat iOS13' do
    use_frameworks!

    # Pods for Flash Chat iOS13
    pod 'Firebase/Auth'
    pod 'Firebase/Storage'
    pod 'Firebase/Firestore'
    pod 'CLTypingLabel', '~> 0.4.0'
    
end
